# Generated by Django 5.0.7 on 2024-11-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_education_professionalexperience_resume_resumeskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='heroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('background_image', models.ImageField(upload_to='hero_images/')),
                ('button_text', models.CharField(max_length=100)),
                ('button_link', models.URLField()),
            ],
        ),
    ]
